
[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Underline"
blinking = "on"

[font]
size = 10

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
# opacity = 0.5
dynamic_title = false

[window.dimensions]
columns = 90
lines = 30

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 0

[general]
import = [
  #"~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/oh-lucy.toml"
]

[terminal]
